# Generated by Django 5.0.6 on 2024-05-23 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murojaat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255)),
                ('ish_joyi', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('hudud', models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax'), ('Qashqadaryo', 'Qashqadaryo'), ('Navoiy', 'Navoiy'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Toshkent', 'Toshkent'), ('Fargona', 'Fargona'), ('Xorazm', 'Xorazm'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=255)),
                ('murojaat_turi', models.CharField(choices=[('murojaat', 'Murojaat'), ('taklif', 'Taklif'), ('shikoyat', 'Shikoyat'), ('talabnoma', 'Talabnoma'), ('bosh_ish_orin', 'Bosh_ish_orin'), ('rahbariyat_qabuli', 'Rahbariyat_qabuli'), ('sayt_mamuriyatiga', 'Sayt_mamuriyatiga')], max_length=255)),
                ('murojaat_mavzusi', models.CharField(max_length=255)),
                ('murojaat_matni', models.CharField(max_length=255)),
                ('murojaat_fayli', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
