# Generated by Django 5.0.6 on 2024-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murojaat', '0002_murojaat_delete_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murojaat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='murojaat',
            name='user',
        ),
        migrations.AlterField(
            model_name='murojaat',
            name='status',
            field=models.CharField(choices=[('pending', 'Korib chiqilmoqda'), ('accepted', 'Qabol qilindi'), ('rejected', 'Rad etildi'), ('answered', 'Javob berildi')], default='pending', max_length=10),
        ),
    ]
